<?php $file = basename(__FILE__, '.php'); ?>
<?php include('php/header.php') ?>
<div class="container container-main">
	<div class="row">
		<div class="col-md-8">
			<p class="text-justify">Although much has been written about Balkan endemic nephropathy (BEN) over the past 50 years, its precise etiology is still unknown, similar to other chronic kidney disease and rather intuitive multiple factors are to be taken into account. Along time many factors have been proposed as etiological agents – bacteria and viruses, heavy metals, (Pb, Cd etc.), industrial pollution, genetic factors and even astrological influences. In recent years many research groups have turned their attention to aristolochic acid (AA), a nephrotoxic and carcinogenic substance produced by the plant Aristolochia clematitis. Since BEN has similarities in patho-morphological characteristics with Chinese herbal nephropathy, a common etiology (toxic effect of the aristolochic acid) of both disorders was proposed (Staneva et al.2013). Poisoning with aristolochic acids is now one of the widely accepted factors responsible of triggering BEN, but aristolochic acid hypothesis does not explain issues like geographic restriction of the disease (A. clematitis is a plant that grows equally in endemic and non-endemic areas), and remains to be clarified what is the exact route of exposure to AA, and how AA gets to contaminate the human population. The existence of cofactors, which could explain the geographical delimitation of the disease and which could act in synergistic or additive combination with AA becomes very plausible.</p>
			<p class="text-justify">Preliminary studies conducted in endemic areas, have identified the presence of Aristolochic acid (AA ) in soil samples taken from endemic areas, making it very plausible its presents in dust in the atmosphere. One of the hypotheses that we want to prove by this study is the main route of exposure to aristolochic acids of BEN population by air, dust and aerosols. An alternative hypothesis, widely supported in the current literature is the digestive exposure, to Aristolochia acid contamination of wheat flour. The preliminary research conducted on flour samples taken from various endemic areas from Romania and Serbia, failed to identify the presence of Aristolochic acids using a very sensitive method of chromatography, HPLC spectrometry mass ( HPLC -MS ).</p>
			<p class="text-justify">Drinking water quality is influenced by hydrogeological processes, which include the interaction between groundwater and soil interaction with roca, evapotranspiration processes, atmospheric wet and dry deposition, with influences on the local hydrological and hydro chemical processes conditions, occurring in the groundwater. This variability is sometimes difficult to documented, especially in the context of that groundwater impacts it has on the health of the population. Humic acids contaminate many water sources and despite sustained research in this area, there are quite a few on the origin, formation of their structure and chemistry, as well as the impact they have on the environment. By far, the most important draw in terms of environmental impact is HA fraction, capable of physically and chemically interactions with many other organic and inorganic compounds, changing their solubility, chemical reactivity, their bioavailability from the aquifer and their extractive capacity from base rock. For example, interaction between arsenic and humic acids is suspected because can worsen the effects of this toxic metal (Anawar et al., 2002). However, much less is known about the HA role as etiopatogenic factors or cofactors in the genesis of diseases in humans, as a result of exposure to these compounds in drinking water (Ho et al., 2003 Cheng et al., 1999, Huang et al., 1994, Sato y et al., 1986).</p>
			<p class="text-justify">All the data related to BEN and chronic kidney disease in generally indicate the existence of complex interactions between environment and genetics of individuals who develop this condition, and only certain aspects can explain the fact that certain subjects in these affected areas are susceptible to chronic kidney disease (CKD) and kidney failure. Familial clustering of BEN patients suggests a genetic predisposition of the disease. The epigenome and the epigenetic mechanisms controlling our gene expression in response to environment together with lecithin-cholesterol acyltransferase deficiency (LCAT) (Pavlovic et al., 2008) or particularities of xenobiotics genetic metabolism (CYP450, NQO, GST) are possible candidates for the genetic specificity of the disease. Each of these factors in part is probably insufficient to cause the BEN. However, when combined, they could induce chronic nephropathy and renal failure.</p>
		</div>
		<div class="col-md-4">
	  		<img alt="500x500" class="img-responsive center-block img-rounded" src="images/zone_endemice.jpg">
		</div>
	</div>	
</div>
<?php include('php/footer.php') ?>